Add KB for CRLF injection
Ostorlab/KB pull request #112
Opened 2024-01-05 15:28 UTC by BlueSquare1

2024-01-05 15:44 UTC, rabsondev approved these changes

2024-01-05 15:56 UTC, ErebusZ commented on WEB_SERVICE/WEB/_HIGH/HTTP_HEADER_INJECTION/description.md
> +=== Request
I think these should be examples on the configuration, not the request

2024-01-05 18:14 UTC, 3asm commented on WEB_SERVICE/WEB/_HIGH/HTTP_HEADER_INJECTION/description.md
> +=== Response
Example of vulnerable code is missing.

2024-01-09 08:55 UTC, 3asm requested changes

2024-01-09 08:55 UTC, 3asm commented on WEB_SERVICE/WEB/_HIGH/HTTP_HEADER_INJECTION/description.md
> +=== Response
Ping.

2024-01-09 13:33 UTC, 3asm approved these changes

2024-01-09 13:33 UTC, merged