Adding NOSQL injection entry
Ostorlab/KB pull request #114
Opened 2024-01-08 10:14 UTC by PiranhaSa

2024-01-08 10:32 UTC, elyousfi5 commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +By injecting crafted input, attackers aim to alter the logic of database queries, bypass authentication, or retrieve sensitive information stored in the database. NoSQL injection attacks can lead to
```suggestion
By injecting the crafted input, attackers aim to alter the logic of database queries, bypass authentication, or retrieve sensitive information stored in the database. NoSQL injection attacks can lead to unauthorized data access, data modification, or even the complete compromise of the database, compromising the confidentiality, integrity, and availability of the application and its data.
```

2024-01-08 11:06 UTC, rabsondev requested changes

2024-01-08 11:06 UTC, rabsondev commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +### Examples
The code samples should have the same format as the code below so that they're shown as tabs in the UI.

```
=== Request
  ```http
  GET /?page=login%0D%0ACustom-Header:%20vulnerable HTTP/1.1
  Host: localhost
  User-Agent: Mozilla/5.0
  Referrer: http://localhost/
```

You can refer to this PR to see how it's done.

2024-01-08 11:06 UTC, elyousfi5 commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/meta.json
> +    "PCI_STANDARDS": [
I think "REQ_6_2" and "REQ_6_3", should be added as well:
![image](https://github.com/Ostorlab/KB/assets/144013278/9f0a3c18-950a-46bb-8bed-467d437dc5b0)

2024-01-08 11:07 UTC, BlueSquare1 requested changes

2024-01-08 11:07 UTC, BlueSquare1 commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/meta.json
> +      "CWE_918",
`CWE-918` is for SSRF

2024-01-08 11:07 UTC, BlueSquare1 commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/recommendation.md
> +    }
Should have some sanitization logic here.

2024-01-08 13:30 UTC, amine3 approved these changes

2024-01-09 08:51 UTC, 3asm requested changes

2024-01-09 08:51 UTC, 3asm commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +                query.put("password", password);
Are you sure this is vulnerable?

2024-01-09 10:20 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +                query.put("password", password);
I've changed it , can you please review the new one

2024-01-09 10:48 UTC, 3asm requested changes

2024-01-09 10:48 UTC, 3asm commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +            // Vulnerable query susceptible to NoSQL Injection
The same comment applies to the other examples.

2024-01-09 11:29 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_CRITICAL/NOSQL_INJECTION/description.md
> +            // Vulnerable query susceptible to NoSQL Injection
For php :  I've changed to be based on this : 
![image](https://github.com/Ostorlab/KB/assets/146742880/0b5f74c2-5f20-465a-8dca-9fb12aab6550)
For js : 
![image](https://github.com/Ostorlab/KB/assets/146742880/75228d77-c0a2-4e3e-af59-469fd9319c0a)

2024-01-09 13:36 UTC, 3asm approved these changes

2024-01-09 13:37 UTC, merged