Redo Android KBs
Ostorlab/KB pull request #138
Opened 2024-03-28 15:49 UTC by BlueSquare1

2024-03-28 16:17 UTC, 3asm requested changes

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/UNTRUSTED_EXTERNAL_STORAGE_ACCESS/description.md
This one should stay.

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/recommendation.md
> +* Custom Certificate Authority with support for debug only settings
Not actionable. What should I do?

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HARDENING/APK_NOT_OBFUSCATED/recommendation.md
> +Design the application with the following protections to make it harder to reverse engineer it:
Design?

Not actionable, what should I do?

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_LOW/APK_LIST_NOT_USED_PERMISSIONS/recommendation.md
> +Remove unused declared permissions from the application's manifest
Please provide a code example.

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_LOW/INTENT_SPOOFING/recommendation.md
> +To limit one's exposure to this type of attack, developers should:
```suggestion
To limit one's exposure to this type of attack, consider the following recommendations: 
```

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_LOW/INTENT_SPOOFING/recommendation.md
> +specifically designed to handle requests from untrusted applications.
Don't break line on full sentences. It breaks in the UI.

2024-03-28 16:17 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_LOW/PRIVACY_KEYBOARD_CACHE/recommendation.md
> +Sensitive input fields should be marked as `password` input field to avoid having sensitive data logged into keyboard cache.
Need a better recommendation.

2024-03-28 16:32 UTC, benyissa commented on MOBILE_CLIENT/ANDROID/_HARDENING/APK_ELF_NOTPROTECTED/recommendation.md
> +To ensure that the Stack canary feature is enabled when compiling with GCC, you can specify one of the compiler options:
```suggestion
To ensure that the stack canary feature is enabled when compiling with GCC, you can specify one of the compiler options:
```

2024-03-28 16:32 UTC, benyissa commented on MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/recommendation.md
> +Android Network Security Configuration enables a declarative setting of the application network security.
```suggestion
Android Network Security Configuration enables a declarative setting of the application's network security.
```

2024-03-28 16:47 UTC, amine3 submitted a review, later dismissed

2024-03-29 08:53 UTC, ErebusZ reviewed
it might be worth splitting this PR.

2024-03-29 09:23 UTC, BlueSquare1 commented on MOBILE_CLIENT/ANDROID/_MEDIUM/UNTRUSTED_EXTERNAL_STORAGE_ACCESS/description.md
I replaced it with `INSECURE_STORAGE` KB

2024-03-29 10:11 UTC, BlueSquare1 commented on MOBILE_CLIENT/ANDROID/_HARDENING/APK_INSECURE_NETWORK_SECURITY_CONFIG/description.md
> -* Custom Certificate Authority with support for debug only settings
This is a recommendation code that was put in the vulnerability description

2024-03-29 15:27 UTC, oussamaessaji approved these changes

2024-04-02 10:29 UTC, 3asm commented
@oussamaessaji please stop approving PRs without proper review.

2024-04-02 15:20 UTC, 3asm commented
@BlueSquare1 what is the status of this PR?

2024-04-02 15:26 UTC, BlueSquare1 commented
> @BlueSquare1 what is the status of this PR?

All comments have been addressed, other KB categories will have separate PRs.

2024-04-02 21:04 UTC, 3asm approved these changes

2024-04-02 21:05 UTC, merged