Improve text Insecure File Provider Paths Setting
Ostorlab/KB pull request #16
Opened 2023-02-14 15:55 UTC by najibraihan

2023-02-15 08:36 UTC, 3asm submitted a review, later dismissed

2023-02-15 08:36 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_FILE_PROVIDER_PERMISSIVE_EXTERNAL_PATH/description.md
> +This path grants access to protected parts of the app and of the device.
```suggestion
This path grants access to protected parts of the app and of the device and thus exposes the application filesystem.
```

2023-02-15 08:36 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_FILE_PROVIDER_PERMISSIVE_EXTERNAL_PATH/description.md
> +or `Overwriting arbitrary files` to achieve arbitrary code execution by Overwriting native libraries.
```suggestion
or `Remote Code Execution` by overwriting native libraries.
```

2023-02-15 08:36 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_FILE_PROVIDER_PERMISSIVE_EXTERNAL_PATH/recommendation.md
> +* use specific folders for path attribute:
This part needs more human-friendly text.

2023-02-15 18:27 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_FILE_PROVIDER_PERMISSIVE_EXTERNAL_PATH/recommendation.md
> +* use specific folders for path attribute:
Comment not addressed.

2023-02-16 10:33 UTC, amine3 requested changes

2023-02-16 10:33 UTC, amine3 commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_FILE_PROVIDER_PERMISSIVE_EXTERNAL_PATH/recommendation.md
> +* use specific folders for path attribute:
use specific folders for path attributes

2023-02-16 11:29 UTC, amine3 approved these changes

2023-02-16 11:30 UTC, merged