Feature/add graphql circular fragments
Ostorlab/KB pull request #172
Opened 2024-09-12 16:56 UTC by Zakaria-Latif

2024-09-12 17:10 UTC, oussamaessaji commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/description.md
> +```
I would like to see more examples

2024-09-13 03:44 UTC, 3asm requested changes

2024-09-13 03:44 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/description.md
> +```
Nah this is good enough.

2024-09-13 03:44 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/meta.json
> +    "OWASP_ASVS_L3": [
ASVS_L2?

2024-09-13 03:44 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +### 3. Enforce Depth and Recursion Limits
The recommendation covers more than the scope of the vulnerability.

2024-09-13 07:42 UTC, nmasdoufi-ol commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/meta.json
> +    "OWASP_ASVS_L3": [
An application achieves ASVS Level 3 (or Advanced) if it adequately defends against advanced application security vulnerabilities and also demonstrates principles of good security design. An application at ASVS Level 3 requires more in depth analysis of architecture, coding, and testing than all the other levels.

2024-09-13 07:58 UTC, ohachimOs approved these changes

2024-09-13 08:52 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +```
This will not stop the attack because it needs only one request , so I think it should be removed

2024-09-13 08:53 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +Rather than nesting multiple fragments within each other, use a simpler query like this.
I don't think that an attacker will follow this recommendation

2024-09-13 13:16 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/meta.json
> +    "OWASP_ASVS_L3": [
I don't see how is your comment related?

2024-09-13 13:17 UTC, 3asm requested changes

2024-09-13 13:17 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +### 3. Enforce Depth and Recursion Limits
You haven't address this comment @Zakaria-Latif .

2024-09-13 16:52 UTC, elyousfi5 commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +To prevent circular fragments in GraphQL, consider the following steps:
```suggestion
To mitigate the risk of circular fragments in GraphQL, consider the following steps:
```

2024-09-17 07:58 UTC, ErebusZ approved these changes

2024-09-17 09:00 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +Rather than nesting multiple fragments within each other, use a simpler query like this.
Can you please explain how this will solve the fragment issue

2024-09-17 10:38 UTC, nmasdoufi-ol commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/recommendation.md
> +Rather than nesting multiple fragments within each other, use a simpler query like this.
+1

2024-09-17 11:48 UTC, nmasdoufi-ol commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_CIRCULAR_FRAGMENTS/meta.json
> +    "OWASP_ASVS_L3": [
I thought you were asking for ASVS_L3.

2024-09-17 14:34 UTC, 3asm approved these changes

2024-09-17 14:34 UTC, merged