Add alias batching  brute force
Ostorlab/KB pull request #174
Opened 2024-09-17 17:32 UTC by PiranhaSa

2024-09-17 18:02 UTC, rabsondev approved these changes

2024-09-17 18:07 UTC, oussamaessaji approved these changes

2024-09-17 18:28 UTC, 3asm requested changes

2024-09-17 18:28 UTC, 3asm commented on tests/kb_test.py
> +    "CWE_307",
We don't have this in our KB. You can't just add it.

2024-09-17 18:28 UTC, 3asm commented on WEB_SERVICE/WEB/_LOW/GRAPHQL_ALIAS_BRUTEFORCING/description.md
> +Security Impact of Brute Force Login Using Alias Batching:
```suggestion
```

You don't need this line.

2024-09-18 07:59 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_LOW/GRAPHQL_ALIAS_BRUTEFORCING/description.md
> +Security Impact of Brute Force Login Using Alias Batching:
I removed the impact

2024-09-18 10:16 UTC, merged