Add GraphQL Object Limit Overriding KB Entry
Ostorlab/KB pull request #177
Opened 2024-09-18 12:45 UTC by Zakaria-Latif

This PR adds a new Knowledge Base entry titled `Object Limit Overriding in GraphQL`, detailing the risks and mitigations for this vulnerability.

### Description.md:

- Explains how object limit overriding in GraphQL can lead to DoS attacks and excessive resource usage.
- Discusses potential risks and methods to check for vulnerabilities.

### Meta.json:

- Provides metadata, including risk rating and references.
- Categorizes the issue under relevant security frameworks.

### Recommendation.md:

Offers recommendations to mitigate risks, including:
- Query Complexity Analysis
- Rate Limiting
- Pagination and Limits
- Introspection Control

2024-09-18 12:48 UTC, nmasdoufi-ol commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/meta.json
> +      "CWE_400"
I don't think that `CWE_400` is  part of `CWE_TOP_25`

2024-09-18 13:04 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/meta.json
> +      "CWE_400"
It's a part of it 
![image](https://github.com/user-attachments/assets/fe7eb1c0-138d-4690-8716-f623e7fca43c)

2024-09-18 14:58 UTC, ohachimOs commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/meta.json
> +  "categories": {
`name = """CWE-20: Improper Input Validation"""`
Does this fit?

2024-09-19 13:02 UTC, rabsondev commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/recommendation.md
> +```javascript
Check this PR to see how the code snippets should be written:
https://github.com/Ostorlab/KB/pull/170/files#diff-f260b5b86802c915798f4da04070b5b1c080ca45f30dfd8819e1c309df5340a2

2024-09-19 19:00 UTC, 3asm requested changes

2024-09-19 19:00 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/description.md
> +### How to Check:
Avoid the subsection, also missing code source samples. You can also remove how to check since that is our job.

2024-09-19 19:00 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/recommendation.md
> +### Example Implementation:
You can remove it.

2024-09-20 15:56 UTC, 3asm requested changes

2024-09-20 15:56 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/description.md
> +```
```suggestion
Object Limit Overriding in GraphQL refers to a vulnerability where an attacker can manipulate query arguments to exceed the intended limits of an API. This often involves passing extremely large values to pagination or limit parameters, potentially leading to denial-of-service (DoS) attacks or excessive resource consumption.

Potential risks:

**Denial of Service (DoS):** By requesting an excessive number of objects, attackers can overwhelm the server, causing performance degradation or outages.

**Resource Exhaustion:** Queries requesting a vast number of objects can overload the server's memory and processing capabilities.

**Data Exposure:** In some cases, bypassing limits could lead to unauthorized access to large amounts of data.

**Increased Costs:** For cloud-based services, processing queries with extremely large limits may result in unexpected costs due to high resource usage.

Vulnerable Query Example:

```graphql
query {
  users(first: 1000000) {
    id
    name
    email
  }
}
```
```

2024-09-20 15:56 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/meta.json
> +      "CC_9_1"
A bit too much. How come?

2024-09-20 15:56 UTC, 3asm commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/recommendation.md
> +### Example Implementation:
```suggestion
Example Implementation:
```

2024-09-20 17:05 UTC, Zakaria-Latif commented on WEB_SERVICE/WEB/_MEDIUM/GRAPHQL_OBJECT_LIMIT_OVERRIDING/meta.json
> +      "CC_9_1"
updated to more convenient ones

2024-09-21 03:21 UTC, 3asm approved these changes

2024-09-21 03:21 UTC, merged