Add extension bleed SSL KB
Ostorlab/KB pull request #186
Opened 2024-10-02 09:27 UTC by Zakaria-Latif

Add extension bleed SSL KB

2024-10-02 09:29 UTC, elyousfi5 commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/description.md
> +The application is detected to be vulnerable to SSL Extension Bleed, a type of vulnerability that exploits improper handling of SSL/TLS extensions during the handshake process.
This looks like a start of a technical detail. A description should simply define what is the vulnerability.

2024-10-02 13:11 UTC, PiranhaSa commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/meta.json
> +    "CWE-200: Data Exposure": "https://heartbleed.com/",
Why you have the CWE as a title for website that explain the whole vulnerability? I think you can change the title and add another link for the CWE : https://cwe.mitre.org/data/definitions/200.html

2024-10-02 13:15 UTC, ybadaoui-ostorlab approved these changes

2024-10-02 13:19 UTC, 3asm requested changes

2024-10-02 13:19 UTC, 3asm commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/recommendation.md
> +  - **Validation:** Regularly review the configuration of your web servers, load balancers, and any proxies handling SSL/TLS to ensure compliance with best practices.
I really don't like this format action best practice, validation. Is simpler recommendation not possible?

2024-10-02 16:00 UTC, ohachimOs commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/description.md
> +- **Hijack Sessions:** If session keys are disclosed, attackers may gain unauthorized access to existing SSL sessions, allowing them to access user accounts or sensitive information without permissio
We need an example

2024-10-03 07:57 UTC, nmasdoufi-ol commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/description.md
> +An attacker who can repeatedly initiate SSL/TLS handshakes may craft malicious SSL extensions or probe the server in a way that causes the server to unintentionally leak data from memory during the h
```suggestion
An attacker who can repeatedly initiate SSL/TLS handshakes may craft malicious SSL extensions or probe the server to unintentionally leak data from memory during the handshake. As a result, the attacker might recover session keys used in earlier connections, which could then be used to decrypt previously encrypted communication or hijack active user sessions.
```

2024-10-03 08:05 UTC, deadly-panda commented on WEB_SERVICE/WEB/_POTENTIALLY/SSL_EXTENSION_BLEED/description.md
> +An attacker who can repeatedly initiate SSL/TLS handshakes may craft malicious SSL extensions or probe the server in a way that causes the server to unintentionally leak data from memory during the h
I would  expect more details on how these malicious SSL extensions or how the server can unintentionally leak data..

2024-10-03 08:36 UTC, PiranhaSa approved these changes

2024-10-03 09:41 UTC, elyousfi5 approved these changes

2024-10-03 17:59 UTC, 3asm approved these changes

2024-10-03 17:59 UTC, merged