Add DNS wildcard domains KB
Ostorlab/KB pull request #218
Opened 2024-10-21 10:56 UTC by Zakaria-Latif

Add DNS wildcard domains KB

2024-10-21 11:01 UTC, PiranhaSa commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/meta.json
> +      "CC_9_1"
```suggestion
```

2024-10-21 11:12 UTC, elyousfi5 commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/meta.json
> +  "risk_rating": "high",
im not sure if this should be high

2024-10-21 13:07 UTC, Zakaria-Latif commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/meta.json
> +  "risk_rating": "high",
I found that the risk depends on the use case:
- Low Risk: If the wildcard domain is in a controlled environment with strict security policies and proper configuration.
- Medium Risk: If used with weaker controls, exposing potential vulnerabilities.
- High Risk: If misconfigured, leaving subdomains exposed to exploitation, phishing, or data leaks.

Do you think we should lower its risk rating? I tend to go with the highest risk possible.

2024-10-21 16:53 UTC, ohachimOs commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/meta.json
> +      "ART_12",
I don't see this one

2024-10-21 16:54 UTC, ohachimOs commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/meta.json
> +      "ART_5",
I don't think this one applies

2024-10-22 03:49 UTC, 3asm requested changes

2024-10-22 03:49 UTC, 3asm commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/description.md
> +- **Create Phishing Subdomains:** Attackers can easily set up phishing websites using subdomains of a wildcard domain, making them look legitimate.
Really, how?

2024-10-22 03:49 UTC, 3asm commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/description.md
> +- **Subdomain Takeover:** If the hosting service for a wildcard domain is misconfigured or abandoned, attackers may take control of subdomains and use them for malicious purposes.
That's subdomain takeover, a vulnerability on its own, unrelated to wildcards.

2024-10-22 07:56 UTC, ErebusZ commented on WEB_SERVICE/DNS/_HIGH/DNS_WILDCARD_DOMAINS/description.md
> +### Example Scenario:
I think the example should contain a vulnerable implementation instead of a scenario

2024-10-22 09:22 UTC, closed without merging