XPath injection kb entry
Ostorlab/KB pull request #58
Opened 2023-06-22 15:02 UTC by ErebusZ

XPath injection kb entry.

2023-06-23 07:55 UTC, 3asm requested changes

2023-06-23 07:55 UTC, 3asm commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/description.md
> +    println("Hello, $name!")
Where is the XPath vulnerability here?

2023-06-23 07:55 UTC, 3asm commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/meta.json
> +    }
The formatting of this seems off.

2023-06-23 07:55 UTC, 3asm commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
> +To mitigate XPath Injection vulnerabilities, it is important to properly validate and sanitize user input before using it in XPath queries. This can be done by using parameterized queries or prepared
There parametrized queries on xpath?

2023-06-23 07:55 UTC, 3asm commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
> +    val userInput = readLine() ?: ""
I don't see the issue here.

2023-06-23 13:58 UTC, ErebusZ commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/meta.json
> +    }
[0285859](https://github.com/Ostorlab/KB/pull/58/commits/0285859eaa66eb530bf095a3e3bbf4711eeab044)

2023-06-23 14:01 UTC, ErebusZ commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
> +To mitigate XPath Injection vulnerabilities, it is important to properly validate and sanitize user input before using it in XPath queries. This can be done by using parameterized queries or prepared
depends on the package but yes, as far as I understand

2023-06-23 14:01 UTC, ErebusZ commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/description.md
> +    println("Hello, $name!")
[3e35e7e](https://github.com/Ostorlab/KB/pull/58/commits/3e35e7e983b4e854c4e61952b620b54b4fa82837)

2023-06-23 14:24 UTC, ErebusZ commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
> +    val userInput = readLine() ?: ""
[d270584](https://github.com/Ostorlab/KB/pull/58/commits/d27058446edcfd6aedc081445ea756617e2dec5a), please double check the new snippet, also this one uses parameterized query.

2023-06-25 18:52 UTC, 3asm requested changes

2023-06-25 18:52 UTC, 3asm commented on MOBILE_CLIENT/COMMON/_HIGH/XPATH_INJECTION/recommendation.md
> +    val expression = xpath.compile(xpathQuery)
Isn't this still vulnerable?

2023-06-27 16:48 UTC, 3asm approved these changes

2023-06-27 16:48 UTC, merged