Optimize insecure class loading kb.
Ostorlab/KB pull request #69
Opened 2023-07-31 16:12 UTC by oussamaessaji

2023-07-31 18:07 UTC, 3asm requested changes

2023-07-31 18:07 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_CLASS_LOADING/description.md
> +**Example code in Android:**
Missing other languages, also the format do not respect the new template.

2023-07-31 18:07 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_CLASS_LOADING/recommendation.md
> +```javascript
javascript?

2023-07-31 18:07 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_CLASS_LOADING/recommendation.md
> +- Enable Code Obfuscation: Consider using code obfuscation techniques to make the dynamically loaded code harder to reverse engineer. Obfuscation can help protect sensitive information and intellectu
All of these need to show in the code example!

2023-08-01 13:09 UTC, BlueSquare1 requested changes

2023-08-04 06:43 UTC, 3asm requested changes

2023-08-04 06:43 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_CLASS_LOADING/description.md
> +    MirrorSystem mirrorSystem = currentMirrorSystem();
I thinks mirros don't work on Mobile.

2023-08-04 06:43 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_MEDIUM/INSECURE_CLASS_LOADING/recommendation.md
> +# Class Loading Hijacking
```suggestion

```

2023-08-04 16:08 UTC, 3asm approved these changes

2023-08-04 16:08 UTC, merged