Feature/support gdpr compliance regulation
Ostorlab/KB pull request #77
Opened 2023-10-02 16:43 UTC by oussamaessaji

2023-10-02 17:37 UTC, 3asm requested changes

2023-10-02 17:37 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_BIOMETRIC_AUTHENTICATION_BYPASS/meta.json
> +    ],
You first need to add the rules to RE. Add them with a key and mention the key here.

2023-10-02 20:20 UTC, amine3 requested changes

2023-10-02 20:20 UTC, amine3 commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_BIOMETRIC_AUTHENTICATION_BYPASS/meta.json
> +      "Article 25 - protection by design and by default"
You should add the GDPR category in scan_categories in RE and just mention the key here.

2023-10-03 17:35 UTC, amine3 approved these changes

2023-10-04 04:43 UTC, 3asm requested changes

2023-10-04 04:43 UTC, 3asm commented on MOBILE_CLIENT/ANDROID/_HIGH/APK_BIOMETRIC_AUTHENTICATION_BYPASS/meta.json
> +      "art_32"
Can you change them to all caps.

2023-10-04 04:55 UTC, 3asm requested changes

2023-10-04 04:55 UTC, 3asm commented on MOBILE_CLIENT/IOS/_MEDIUM/IPA_URL_SCHEME_HIJACKING/meta.json
> +    ],
I don't see any mentions of article 24 and 44 in the findings. 44 is related to data transfer. 24 is related to data processing.

2023-10-04 18:28 UTC, 3asm approved these changes

2023-10-04 18:28 UTC, merged